### ISSUE TITLE
Usage with VS Code

### ISSUE THREAD

**Issue by FakeShemp** [flathub/org.freedesktop.Sdk.Extension.node10#1]
Thanks for the extension. 

Is it possible to use with VS Code? I cannot seem to get `node` recognized.

**Comment by gasinvein** [comment]
Does VS Code allow specifying full path to the `node` binary? It's located in `/usr/lib/sdk/node10/bin`.

**Comment by FakeShemp** [comment]
Yes it does. I can see it now when listing the full path. Thank you, this issue is solved.
