### ISSUE TITLE
freedesktop 19.08 support

### ISSUE THREAD

**Issue by ovari** [flathub/org.freedesktop.Sdk.Extension.node10#3]
Can you please advise when you will support the new freedesktop 19.08 runtime?
https://github.com/flathub/org.mozilla.Thunderbird/issues/62#issuecomment-530605516

Thank you

**Comment by refi64** [comment]
I'll be able do it by the end of the weekend at the very latest.

**Comment by refi64** [comment]
Okay I pushed it, let's see how the [build](https://flathub.org/builds/#/builders/32/builds/8241) goes.

**Comment by refi64** [comment]
Looks like it's good to go! (Still uploading, but the build was a success.)

**Comment by ovari** [comment]
> I can't build TB with current runtime due to some clang error, see [#73](https://github.com/flathub/org.mozilla.Thunderbird/pull/73)
I plan to try with new freedesktop 19.08 runtime but first I need [org.freedesktop.Sdk.Extension.node10](https://github.com/flathub/org.freedesktop.Sdk.Extension.node10) to support it.
https://github.com/flathub/org.mozilla.Thunderbird/issues/62#issuecomment-530571764

@Erick555 can you now build Thunderbird 68.1.0 for Flatpak? Thank you
