### ISSUE TITLE
error: Failed to install org.freedesktop.Platform.openh264: While trying to apply extra data: runtime/org.freedesktop.Platform/x86_64/19.08 not installed

### ISSUE THREAD

**Issue by ovari** [flathub/org.freedesktop.Sdk.Extension.node10#4]
Error installing Thunderbird (Flathub) via Mint's Software Manager #260
https://github.com/linuxmint/mintinstall/issues/260

_flatpak.py: Don't fail an entire job if one package fails to install #36
https://github.com/linuxmint/mintcommon/pull/36

Thunderbird can't be found on flathub.org #62
https://github.com/flathub/org.mozilla.Thunderbird/issues/62

**Comment by refi64** [comment]
I'm not seeing how this relates to...any of those issues.
