### ISSUE TITLE
Any plans for a node12 extension?

### ISSUE THREAD

**Issue by mbooth101** [flathub/org.freedesktop.Sdk.Extension.node10#9]
I believe node 12 is the current upstream LTS version, any plans for a node12 extension for freedesktop SDK?

**Comment by refi64** [comment]
I've had this in the back of my mind for a while, and it resurfaced again when I saw that Sublime Text needs node12. However I'm *really* busy atm and have many other things that are higher priority right now...

**Comment by gasinvein** [comment]
This should be easy enough - just copy this repo and replace "node10" with "node12".

**Comment by mbooth101** [comment]
FWIW, I submitted a PR to add a node12 extension (see https://github.com/flathub/flathub/pull/1367)

**Comment by bilelmoussaoui** [comment]
Thanks @mbooth101 :)
